# Generated by Django 3.1.2 on 2020-11-01 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jetlendapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('jetlendapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('passport', models.IntegerField()),
                ('birth', models.DateField()),
                ('placeofbirth', models.CharField(choices=[('Msc', 'Moscow'), ('Spb', 'Saint-Petersburg'), ('Ufa', 'Ufa'), ('Alb', 'Albuquerque'), ('Frg', 'Fargo'), ('etc', 'etc.')], default='Msc', max_length=32)),
                ('dateofissue', models.DateField()),
                ('districtcode', models.IntegerField()),
                ('districtname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(default=1, on_delete=models.SET(jetlendapi.models.get_deleted_user), related_name='owner_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_file', models.FileField(blank=True, null=True, upload_to='media/covers/%Y/%m/%D/')),
                ('gallery_passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jetlendapi.identifier')),
            ],
        ),
    ]
