# Generated by Django 3.1.2 on 2020-11-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetlendapi', '0003_policyagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyagreement',
            name='agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policyagreement',
            name='rules',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policyagreement',
            name='tax',
            field=models.BooleanField(default=False),
        ),
    ]
